# Generated by Django 4.0.5 on 2022-08-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answered_correctly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
