# Generated by Django 4.0.5 on 2022-08-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ_app', '0003_alter_test_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
