# Generated by Django 4.0.5 on 2022-08-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ_app', '0004_test_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='creator',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
