# Generated by Django 4.0.5 on 2022-08-16 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ_app', '0005_remove_test_creator_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='importance',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
