# Generated by Django 4.1.1 on 2022-10-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univ_app', '0015_alter_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, default='test.png', upload_to='uploads/Y%/%m/%d/'),
        ),
    ]
