# Generated by Django 4.1.1 on 2022-10-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univ_app', '0016_alter_test_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(blank=True, default='test.png', null=True, upload_to='uploads/Y%/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Given_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('related_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='univ_app.answer')),
            ],
        ),
    ]
