# Generated by Django 4.1.1 on 2022-10-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ_app', '0017_alter_test_image_given_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Given_Answer',
            new_name='GivenAnswer',
        ),
    ]
