# Generated by Django 4.1.1 on 2022-10-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('univ_app', '0020_takentest_related_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givenanswer',
            name='related_answer',
        ),
    ]
